### ISSUE TITLE
Build objects under fft/ only

### ISSUE THREAD

**Issue by Wetitpig** [wbhart/mpir#244]
I am trying to create object files for the C script in thw fft/ directory.

When I try to link them with libgmp, a lot of fatal errors specifying undefined reference were emitted. How to fix that? I would like to integrate only the files within the directory within libgmp, without other files. Thanks!

**Comment by wbhart** [comment]
You can't do this. Code in the fft directory depends on a lot of the rest
of MPIR.

**Comment by Wetitpig** [comment]
Oh. So can you please add the assembly in the GMP 6.1.2? Otherwise it runs 2x slower. :(

**Comment by wbhart** [comment]
There is an open ticket for this. At least for Broadwell, Skylake and
Haswell, this work might actually be underway. No one is working on
speeding up AMD or more recent Intel processors at present. (Patches
welcome.)

Can you give an explicit example of a piece of code that runs twice as
slow. This might help motivate the work underway. Also, what does
./config.guess return on your machine (so we know what system you are
working with).

**Comment by wbhart** [comment]
You can track the progress on speeding up Broadwell (and probably Haswell
and Skylake) at Pull Request 243

https://github.com/wbhart/mpir/pull/243

On the other hand, I doubt assembly language improvements make a 2x
difference. It's more likely someone has contributed faster C code to GMP,
which is why we would need to know which functions you are calling to be
able to help.

**Comment by Wetitpig** [comment]
Ok my system is armv8l-unknown-linux-gnueabi ( an Android phone ).

When I am testing the primality of 2^11213-1 with libgmp, it takes 0.887 seconds, but it takes 1.59 seconds with this library.

**Comment by Wetitpig** [comment]
The functions I call are mpn_sqr() mpn_sub() mpn_rshift() mpn_and_n() mpn_xor_n() mpn_add_n() mpn_sizeinbase() mpn_com()

**Comment by wbhart** [comment]
Thanks for the information.

Firstly, the GMP function for testing primality isn't actually a primality
test. It's a pseudoprimality test. If you want to test primality of numbers
that large, use Pari/GP and you will need a decent computer, not a phone.

Secondly, we aren't putting effort into assembly for mobile phones. We are
focused on speeding up serious hardware. Certainly the work on Broadwell
that I spoke of, isn't going to help you.

The GMP project does have good assembly for Arm, and I recommend using GMP
instead of MPIR in this case. Of course patches to speed up MPIR on Arm are
welcome, but it's a lot of work.

**Comment by Wetitpig** [comment]
But the problem also affects iMacs which run on Intel. I have done the test for 2^86243-1 on iMac in 8.57s with GMP, but 19s with MPIR.

**Comment by wbhart** [comment]
I assume you are doing a Lucas primality test here? If so, then the
bottleneck may be in the FFT. Perhaps GMP has new FFT code?

Also, what does your iMac recognise as? What is the result of
./config.guess in MPIR.

It's not likely that a 2x speedup is due to assembly language, I think.

**Comment by Wetitpig** [comment]
It should be x86_64 skylake. I thought that the FFT module here will speed things up in libgmp...

**Comment by wbhart** [comment]
Yes, but what's the output of config.guess?

**Comment by Wetitpig** [comment]
I am not with my iMac now, may nered to reply 12 hours later

**Comment by Wetitpig** [comment]
`Wetitpigs-iMac:gmp-6.1.2 cowpig$ ./config.guess
kabylake-apple-darwin17.3.0`

**Comment by wbhart** [comment]
I don't see how this can be the result of config.guess in MPIR. We don't
detect kabylake at all. It's too recent!

Have you by chance used config.guess in GMP?

**Comment by Wetitpig** [comment]
Oh, are they different? Btw, here is the version by this config.guess:
`x86_64-apple-darwin17.3.0`

**Comment by wbhart** [comment]
Ah, that shows your CPU is not being detected.

Try doing:

./configure --build=skylakeavx-apple-darwin17.3.0
make clean
make

This won't configure it for your cpu, since we don't have any support for
it. But it will certainly configure it with assembly code written for
something similar.

**Comment by wbhart** [comment]
You may also need to do make install, of course, depending on how you are
using MPIR.

**Comment by Wetitpig** [comment]
Thanks
