### ISSUE TITLE
Error in gmp-h.in on 64bit Windows

### ISSUE THREAD

**Issue by madscientist** [wbhart/mpir#248]
There's an error in gmp-h.in which causes MPIR use on Windows 64bit to fail:
```
#ifdef __WIN64
#define _LONG_LONG_LIMB 1
#endif
```
Is wrong: there's no such constant as `__WIN64` (two underscores) on Windows.  You want `_WIN64` instead:
```
#ifdef _WIN64
#define _LONG_LONG_LIMB 1
#endif
```

**Comment by wbhart** [comment]
Can you be more specific about the failure you are referring to? That macro is defined by both gcc and clang on Windows 64. [1]

[1] http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system

**Comment by madscientist** [comment]
I can't access that link, unfortunately; I get a timeout.

In any event `__WIN64` is not defined by Microsoft Visual Studio.  the standard macros on Windows are [documented here](https://msdn.microsoft.com/en-us/library/b0084kay.aspx).

When I compile with Visual Studio, that macro is not defined and that means that `_LONG_LONG_LIB` is not defined, and that means that `mp_limb_t` is defined to be `unsigned long int` which is 32bit (Windows is an LLP64 system where `long` is 32bits) instead of `unsigned long long int` as it should be.

This causes compile errors, etc. due to mismatched types when you try to invoke MPIR functions with `long long` values.

**Comment by wbhart** [comment]
mpir.h is generated by the Windows build files when using MSVC. There is no
reason you should need gmp-h.in. My guess is the macro in use there is on
purpose, not accidental. It prevents people using the wrong file.

**Comment by wbhart** [comment]
Perhaps @BrianGladman recalls something about this?

**Comment by BrianGladman** [comment]
When building with MSVC, lines 73 to 75 in gmp_h.in have no effect since earlier generated parts of mpir.h already define _LONG_LONG_LIMB (in a section that is active when _GMP_WITHIN_CONFIGURE is NOT defined).   

The three lines in question are active when _GMP_WITHIN_CONFIGURE is defined, which I believe will occur when MPIR for Windows is being built using GCC with mingw, cygwin or their 64-bit equivalents, in which case I believe __WIN64 will be defined. 

So until we know whether MSVC or GCC is being used, it is not possible to work out what might have gone wrong.  But either way, I doubt that the failure is caused by an error in gmp_h.in

**Comment by madscientist** [comment]
Oops, you're right.  I have a unified Git repository with pre-built versions of third party tools across three different platforms (GNU/Linux, MacOS, Windows).  I do use MSVC on Windows (I did mention that above).  I was accidentally using the GNU/Linux MPIR headers when compiling on Windows.  Once I sorted that, it worked fine.  Interesting that once I changed that one macro in the GNU/Linux mpir.h, it worked fine with my MSVC build on Windows as well.

Unfortunately the MacOS build seems broken in a way I haven't been able to figure out and I've had to drop back to MPIR 2.6.0.  But that's a different issue, if I get enough detail to file it.

Sorry for the noise!
